# Generated by Django 3.2.17 on 2023-03-01 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='expense_amount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
