# Generated by Django 3.2.17 on 2023-03-07 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_alter_post_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
